---
# defaults file for orahost-logrotate
oracle_base: /u01/app/oracle

logrotate_config:
        - name: oracle_alert
          file: "{{ oracle_base }}/diag/rdbms/*/*/trace/*alert*.log {{ oracle_base }}/diag/asm/*/*/trace/alert*+ASM*.log"
          options:
            - missingok
            - notifempty
            - weekly
            - rotate 3
            - dateext
        - name: oracle_listener
          file: "{{ oracle_base }}/diag/tnslsnr/*/*/trace/*listener*.log"
          options:
            - missingok
            - notifempty
            - weekly
            - rotate 3
            - dateext
            - compress
