---

  master_node: true

  oracle_user: oracle                        # User that will own the Oracle Installations.
  grid_user: grid
  grid_install_user: "{% if role_separation==true %}{{ grid_user }}{% else %}{{ oracle_user }}{% endif %}"
  oracle_user_home: "/home/{{ oracle_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
  grid_user_home: "/home/{{ grid_install_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
  oracle_group: oinstall                          # Primary group for oracle_user.
  oper_group: oper
  dba_group: dba                          # Primary group for oracle_user.
  asmoper_group: asmoper
  asmdba_group: asmdba                          # Primary group for oracle_user.
  asmadmin_group: asmadmin                          # Primary group for oracle_user.

  hostgroup: "{{ group_names[0] }}"
  hostgroup_hub: "{{ hostgroup }}-hub"
  hostgroup_leaf: "{{ hostgroup }}-leaf"

  install_from_nfs: false
  nfs_server_sw: nfsserver
  nfs_server_sw_path: /path/to/orasw
  oracle_sw_copy: "{% if install_from_nfs==true %}false{% else %}true{% endif %}"
  oracle_sw_unpack: "{% if install_from_nfs==true %}false{% else %}true{% endif %}"
  oracle_db_responsefile: "{{ ansible_hostname }}.rsp"
  oracle_db_run_install: "install_{{ ansible_hostname }}.sh"
  #oracle_db_responsefile: "{% if item.0.oracle_db_name is defined %}{{ item.0.oracle_db_name }}_{{ ansible_hostname }}.rsp{% else %}nodbname_defined_{{ ansible_hostname }}.rsp{% endif %}"
  oracle_stage: /u01/stage
  oracle_stage_remote: "{{ oracle_stage }}"
  oracle_stage_install: "{% if oracle_sw_copy==False and oracle_sw_unpack==False%}{{ oracle_stage_remote }}{% else %}{{ oracle_stage }}{% endif %}"
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_inventory_loc: /u01/app/oraInventory
  oracle_base: /u01/app/oracle
  oracle_home_db: /u01/app/oracle/db

  oracle_hostname: "{{ ansible_fqdn }}"                            # Full (FQDN) name of the host
  oracle_sw_source_www: http://www/orasw     # address to all software if using the get_url module when putting software on the host(s)
<<<<<<< HEAD
  oracle_sw_source_local: /opt  # Path to all software if using the copy module when putting software on the host(s)
=======
  oracle_sw_source_local: /tmp  # Path to all software if using the copy module when putting software on the host(s)
>>>>>>> 071ba98e39314ae133aa9d8c74264b69b4a3f940
  is_sw_source_local: true
  configure_cluster: false
  autostartup_service: false # automatic startup/stop databases service

  glogin_default_nocdb:
        - "set sqlprompt \"_user @ _connect_identifier:>\""
        - "set time on"
  glogin_default_cdb:
        - "define gname=idle"
        - "column global_name new_value gname"
        - "set heading off"
        - "set termout off"
        - "col global_name noprint"
        - "select upper(sys_context ('userenv', 'instance_name') || ':' || sys_context('userenv', 'con_name')) global_name from dual;"
        - "set sqlprompt '_user @ &gname:>'"
        - "set heading on"
        - "set termout on"
        - "set time on"

  oracle_sw_image_db:
       - { filename: linux.x64_11gR2_database_1of2.zip, version: 11.1.0.2 }
       - { filename: linux.x64_11gR2_database_2of2.zip, version: 11.1.0.2 }

  oracle_databases:
    - home: db1
      oracle_version_db: 12.2.0.1
      oracle_edition: EE
      oracle_db_name: orcl
      oracle_db_type: SI
