---
# tasks file for orahost-logrotate

- name: Manage logrotate
  template: src=logrotate.j2 dest=/etc/logrotate.d/{{ item.name }}
  with_items:
        - "{{ logrotate_config }}"
  when: logrotate_config is defined
  tags: logrotate
