---


- name: Host configuration
  hosts: vbox-si-asm
  user: vagrant
  become: yes
  roles:
     - common
     - orahost
     - orahost-storage

- name: Oracle Grid Infrastructure installation & ASM Configuration
  hosts: vbox-si-asm
  user: vagrant
  become: yes
  roles:
     - oraswgi-install
     - oraasm-createdg

- name: Database Server Installation & Database Creation
  hosts: vbox-si-asm
  user: vagrant
  become: yes
  roles:
      - oraswdb-install
      - oradb-create

- name: Install cx_oracle
  hosts: vbox-si-asm
  user: vagrant
  become: yes
  roles:
     - cxoracle

- name: Configure Logrotate
  hosts: vbox-si-asm
  user: vagrant
  become: yes
  roles:
     - orahost-logrotate
